pipeline{

    agent any

    stages{

        stage('Start Grid'){
            steps{
                sh "docker compose -f Selenium-Docker-Runner/grid.yaml up -d"
            }
        }

        stage('Run Test'){
            steps{
                sh "docker compose -f Selenium-Docker-Runner/test-suites.yaml up --pull=always"
            }
        }

    }

    post {
        always {
            sh "docker compose -f Selenium-Docker-Runner/grid.yaml down"
            sh "docker compose -f Selenium-Docker-Runner/test-suites.yaml down"
            archiveArtifacts artifacts: 'output/flight-reservation/emailable-report.html', followSymlinks: false
            archiveArtifacts artifacts: 'output/vendor-portal/emailable-report.html', followSymlinks: false
        }
    }

}
