pipeline{

    agent any

    parameters {
        choice choices: ['chrome', 'firefox'], description: 'Select the browser', name: 'BROWSER'
    }

    stages{

        stage('Start Grid'){
            steps{
                sh "docker compose -f Selenium-Docker-Runner/grid.yaml up --scale ${params.BROWSER}=1 -d"
            }
        }

        stage('Run Test'){
            steps{
                sh "docker compose -f Selenium-Docker-Runner/test-suites.yaml up --pull=always"
                script {
                    if(fileExists('Selenium-Docker-Runner/output/flight-reservation/testng-failed.xml') || fileExists('Selenium-Docker-Runner/output/vendor-portal/testng-failed.xml')){
                        error('failed tests found')
                    }
                }
            }
        }

    }

    post {
        always {
            sh "docker compose -f Selenium-Docker-Runner/grid.yaml down"
            sh "docker compose -f Selenium-Docker-Runner/test-suites.yaml down"
            archiveArtifacts artifacts: 'Selenium-Docker-Runner/output/flight-reservation/emailable-report.html', followSymlinks: false
            archiveArtifacts artifacts: 'Selenium-Docker-Runner/output/vendor-portal/emailable-report.html', followSymlinks: false
        }
    }

}
